DROP PROCEDURE IF EXISTS ADD_KEY_COLUMN_IN_SUGGESTED_SKILL;
CREATE PROCEDURE ADD_KEY_COLUMN_IN_SUGGESTED_SKILL()
    language plpgsql
as $$
BEGIN
ALTER TABLE suggested_skill
    ADD COLUMN suggested_skill_key varchar(300);
END $$;
CALL ADD_KEY_COLUMN_IN_SUGGESTED_SKILL();
DROP PROCEDURE ADD_KEY_COLUMN_IN_SUGGESTED_SKILL;