-- Add education column in profile table

DROP PROCEDURE IF EXISTS ADD_EDUCATION_COLUMN_TO_PROFILE;
CREATE PROCEDURE ADD_EDUCATION_COLUMN_IN_PROFILE()
    language plpgsql
as $$
BEGIN
ALTER TABLE profile
    ADD COLUMN IF NOT EXISTS education varchar(200);
END $$;
CALL ADD_EDUCATION_COLUMN_IN_PROFILE();
DROP PROCEDURE ADD_EDUCATION_COLUMN_IN_PROFILE;
