DROP PROCEDURE IF EXISTS REMOVE_LEVEL_COLUMN_FROM_SKILL;
CREATE PROCEDURE REMOVE_LEVEL_COLUMN_FROM_SKILL()
language plpgsql
as $$
BEGIN
  ALTER TABLE skill
  DROP COLUMN IF EXISTS level;
END $$;
CALL REMOVE_LEVEL_COLUMN_FROM_SKILL();
DROP PROCEDURE REMOVE_LEVEL_COLUMN_FROM_SKILL;